### ISSUE TITLE
Leetcode API Seems to be changed

### ISSUE THREAD

**Issue by tinylic** [tecton/Leetcode-Submission-Downloader#3]
Leetcode API seems to be changed again. We cannot access the whole submission history by simply attaching the page number after 'https://leetcode.com/api/submissions/'.

Could you please have a look at this?

**Comment by lxyjscz** [comment]
fixed in the next pr

**Comment by szotsaki** [comment]
It seems it's changed again:

```
Password:
Check page 1
Traceback (most recent call last):
  File "leetcodeDownloader.py", line 67, in <module>
    checkSubmissions(sys.argv[1], password)
  File "leetcodeDownloader.py", line 47, in checkSubmissions
    trList = r.json()['submissions_dump']
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib64/python2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
